# Generated by Django 2.1.7 on 2019-09-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DOB', models.DateField()),
                ('Mobilenumber', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee information',
            },
        ),
    ]
