# Generated by Django 2.1.7 on 2019-09-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='DOB',
            new_name='emp_DOB',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='Email',
            new_name='emp_Email',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='Firstname',
            new_name='emp_Firstname',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='Mobilenumber',
            new_name='emp_Mobilenumber',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='city',
            new_name='emp_city',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='lastname',
            new_name='emp_lastname',
        ),
    ]
