# Generated by Django 2.1.7 on 2019-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190919_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_DOB',
            field=models.DateField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_Mobilenumber',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
